global:
  ########### common environments
  environments: &sharedEnv
    KAFKA_HOSTS: "PLAINTEXT://dev-kafka1.rarible.int.:9092,dev-kafka2.rarible.int.:9092,dev-kafka3.rarible.int.:9092"
    MONGODB_HOSTS: "dev-mongo1.rarible.int.,dev-mongo2.rarible.int.,dev-mongo3.rarible.int."
    NODE_HOST: "http://dev-node-worker.polygon-node:8545"
    NODE_WEBSOCKETURL: "ws://dev-node-worker.polygon-node:8546"

  ########### Erc20 Indexer environments
  erc20Environments: &erc20Env
    <<: *sharedEnv
    MONGODB_DATABASE: "dev-protocol-polygon-erc20"

  ########### Nft Indexer environments
  nftEnvironments: &nftEnv
    <<: *sharedEnv
    MONGODB_DATABASE: "dev-protocol-polygon-nft"

########### Erc20 Indexer services
polygon-erc20-api:
  environments:
    <<: *erc20Env

polygon-erc20-listener:
  environments:
    <<: *erc20Env

polygon-erc20-migration:
  environments:
    <<: *erc20Env

########### Nft Indexer services
polygon-nft-api:
  environments:
    <<: *nftEnv

polygon-nft-listener:
  environments:
    <<: *nftEnv
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 256

polygon-nft-migration:
  environments:
    <<: *nftEnv

########### Order Indexer services
polygon-order-listener:
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
