global:
  network: ropsten

polygon-nft-listener:
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 256

polygon-order-listener:
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
