common:
  blockchain: mantle
  operatorPrivateKey: "0x0000000000000000000000000000000000000000000000000000000000000000"
  protocolCommission: 0
  featureFlags:
    sudoswapEnabled: false

rarible:
  ethereum:
    cache:
      enabled: true
      expireAfter: 5m
      maxSize: 500
