spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}

parityUrls: ${node.hosts}
parityWebSocketUrls: ${node.webSocketHosts}

jms-brokerUrls: ${broker.jms.hosts}

rarible:
  ethereum:
    httpUrl: ${node.hosts}
    websocketUrl: ${node.webSocketHosts}

blockchain:
  scanner:
    kafka:
      broker-replica-set: ${kafka.hosts}

protocol:
  nft:
    subscriber:
      broker-replica-set: ${kafka.hosts}
  order:
    subscriber:
      broker-replica-set: ${kafka.hosts}
  erc20:
    subscriber:
      broker-replica-set: ${kafka.hosts}
common:
  kafka-replica-set: ${kafka.hosts}
