spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}/?w=1&readConcernLevel=local
common:
  exchange-contract-addresses:
    seaport-v1: "0x00000000006c3852cbef3e08e8df289169ede581"
  transfer-proxy-addresses:
    seaport-transfer-proxy: "0x1e0049783f008a0085193e00003d00cd54003c71"
  order-event-handle:
    parallel: true
    handleSeaport: false
listener:
  handle-approval-after-block: 35953300
rarible:
  seaport:
    network: polygon
