global:
  blockchain: hedera
  network: mainnet

hedera-nft-api:
  image:
    repository: ethereum-indexer-nft-api
  replicas: 2
  service:
    enabled: true
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "app.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "app.env" $ }}/protocol/{{ .Values.global.blockchain }}/nft'
    SPRING_PROFILES_ACTIVE: '{{ .Values.global.blockchain }},core,consul,{{ include "app.env" $ }},{{ .Values.global.blockchain }}-{{ include "app.env" $ }}'
  resources:
    jvm:
      xmx_megabytes: 456
      max_direct_memory_megabytes: 32
  livenessProbe:
    initialDelaySeconds: 180
  updateConfig:
    order: start-first

hedera-nft-listener:
  image:
    repository: ethereum-indexer-nft-listener
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "app.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "app.env" $ }}/protocol/{{ .Values.global.blockchain }}/nft'
    SPRING_PROFILES_ACTIVE: '{{ .Values.global.blockchain }},core,consul,{{ include "app.env" $ }},{{ .Values.global.blockchain }}-{{ include "app.env" $ }}'
  priorityClassName: high
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 32
  livenessProbe:
    initialDelaySeconds: 180

hedera-nft-migration:
  image:
    repository: ethereum-indexer-nft-migration
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "app.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "app.env" $ }}/protocol/{{ .Values.global.blockchain }}/nft'
    SPRING_PROFILES_ACTIVE: '{{ .Values.global.blockchain }},core,consul,{{ include "app.env" $ }},{{ .Values.global.blockchain }}-{{ include "app.env" $ }}'
  priorityClassName: high
  resources:
    jvm:
      xmx_megabytes: 356
      max_direct_memory_megabytes: 32
  livenessProbe:
    initialDelaySeconds: 180
  restartPolicy:
    condition: on-failure
