application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: protocol-${common.blockchain}-erc20-migration
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  codec:
    max-in-memory-size: 50MB
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

mongock:
  change-logs-scan-package:
    - com.rarible.protocol.erc20.migration.mongock

rarible:
  core:
    client:
      name: rarible-protocol
      k8s: true

