spring:
  application.name: protocol-${common.blockchain}-erc20-migration

mongock:
  change-logs-scan-package:
    - com.rarible.protocol.erc20.migration.mongock
    - com.rarible.blockchain.scanner.ethereum.migration

blockchain:
  scanner:
    ethereum:
      scan:
        enabled: false
