global:
  network: rinkeby
  environments: &sharedEnv
    KAFKA_HOSTS: "PLAINTEXT://staging-kafka1.rarible.int.:9092,staging-kafka2.rarible.int.:9092,staging-kafka3.rarible.int.:9092"
    MONGODB_HOSTS: "staging-mongo1.rarible.int.,staging-mongo2.rarible.int.,staging-mongo3.rarible.int."

  ########### Erc20 Indexer environments
  erc20Environments: &erc20Env
    <<: *sharedEnv
    MONGODB_DATABASE: "testnet-protocol-mantle-erc20"

ethereum-erc20-api:
  environments:
    <<: *erc20Env

ethereum-erc20-listener:
  environments:
    <<: *erc20Env

ethereum-erc20-migration:
  environments:
    <<: *erc20Env

mantle-nft-api:
  resources:
    jvm:
      max_direct_memory_megabytes: 128

mantle-order-api:
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128

mantle-order-listener:
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 512

mantle-nft-listener:
  livenessProbe:
    initialDelaySeconds: 360
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 512
