spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}

blockchain:
  scanner:
    kafka:
      numberOfPartitionsPerLogGroup: 100

common:
  scannerProperties:
    skipBlockRange: 47791035..47791134
