spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}
common:
  scanner-properties:
    sender-created-tokens:
      - "0xd4d15a32c2087cf8ca00f448f7337d1c29ec87af"
      - "0xa1cf7d60fc126c5f3a8ce143ebc2db80e0f5a948"