global:
  ########### common environments
  environments: &sharedEnv
    KAFKA_HOSTS: "PLAINTEXT://dev-kafka1.rarible.int.:9092,dev-kafka2.rarible.int.:9092,dev-kafka3.rarible.int.:9092"
    MONGODB_HOSTS: "dev-mongo1.rarible.int.,dev-mongo2.rarible.int.,dev-mongo3.rarible.int."
    RARIBLE_ETHEREUM_NODES_0_HTTPURL: "http://dev-node-worker.ethereum-node:8545"
    RARIBLE_ETHEREUM_NODES_0_WEBSOCKETURL: "ws://dev-node-worker.ethereum-node:8546"

  ########### Erc20 Indexer environments
  erc20Environments: &erc20Env
    <<: *sharedEnv
    MONGODB_DATABASE: "dev-protocol-ethereum-erc20"

  ########### Nft Indexer environments
  nftEnvironments: &nftEnv
    <<: *sharedEnv
    MONGODB_DATABASE: "dev-protocol-ethereum-nft"

########### Erc20 Indexer services
ethereum-erc20-api:
  environments:
    <<: *erc20Env

ethereum-erc20-listener:
  environments:
    <<: *erc20Env

ethereum-erc20-migration:
  environments:
    <<: *erc20Env

########### Nft Indexer services
ethereum-nft-api:
  environments:
    <<: *nftEnv

ethereum-nft-listener:
  environments:
    <<: *nftEnv

ethereum-nft-migration:
  environments:
    <<: *nftEnv
