global:
  ########### common environments
  environments: &sharedEnv
    KAFKA_HOSTS: "PLAINTEXT://staging-kafka1.rarible.int.:9092,staging-kafka2.rarible.int.:9092,staging-kafka3.rarible.int.:9092"
    MONGODB_HOSTS: "staging-mongo1.rarible.int.,staging-mongo2.rarible.int.,staging-mongo3.rarible.int."
    RARIBLE_ETHEREUM_NODES_0_HTTPURL: "http://staging-node-worker.ethereum-node:8545"
    RARIBLE_ETHEREUM_NODES_0_WEBSOCKETURL: "ws://staging-node-worker.ethereum-node:8546"

  ########### Erc20 Indexer environments
  erc20Environments: &erc20Env
    <<: *sharedEnv
    MONGODB_DATABASE: "staging-protocol-ethereum-erc20"

ethereum-erc20-api:
  environments:
    <<: *erc20Env
  livenessProbe:
    initialDelaySeconds: 360

ethereum-erc20-listener:
  environments:
    <<: *erc20Env

ethereum-erc20-migration:
  environments:
    <<: *erc20Env
