global:
  network: rinkeby

ethereum-nft-listener:
  livenessProbe:
    initialDelaySeconds: 360
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

ethereum-gateway:
  service:
    nodePort: 30216