spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}/?w=1&readConcernLevel=local

listener:
  depositTokens:
    - "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6"
