spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}/?w=1&readConcernLevel=local

listener:
  tokens:
    - "0xdeaddeaddeaddeaddeaddeaddeaddeaddead1111" # WETH
    - "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0000" # WMNT
