spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}/?w=1&readConcernLevel=local

listener:
  depositTokens:
    - "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
